base: {{.ConfRootDir}}/hive/common/common.yaml

cluster:
  project: hive
  cluster_name: test-hive
  main_process: java
  package_name: apache-hive-2.3.2-bin.tar.gz
  package_md5sum: 8f3abedb3fba28769afcea1445c64231
  dependencies:
    - {{.ConfRootDir}}/hdfs/test-hdfs.yaml
jobs:
  hiveserver2:
    hosts:
      - 127.0.0.1:9001/id=0/base_port=50100
      - 127.0.0.1:9001/id=1/base_port=50200
  beeline:
    main_entry:
      extra_args: -u jdbc:hive2://127.0.0.1:50100
