language: go

go_import_path: github.com/openinx/huker

go:
  - 1.9.x

# Run coverage tests.
matrix:
  fast_finish: true
  allow_failures:
    - go: 1.9.x

before_install:
  - mkdir -p /tmp/huker

install:
  - export PATH=$PATH:$GOPATH/bin
  - go get github.com/tools/godep
  - godep restore

script:
  - make && make travis-test
