base: {{.ConfRootDir}}/hdfs/common/noha-common.yaml

cluster:
  project: hdfs
  cluster_name: test-hdfs
  main_process: java
  package_name: hadoop-2.6.5.tar.gz
  package_md5sum: 967c24f3c15fcdd058f34923e92ce8ac
  dependencies:
    - {{.ConfRootDir}}/zookeeper/test-zk.yaml

jobs:
  namenode:
    hosts:
      - 127.0.0.1:9001/id=0/base_port=20100
  datanode:
    hosts:
      - 127.0.0.1:9001/id=0/base_port=21000
      - 127.0.0.1:9001/id=1/base_port=21010
      - 127.0.0.1:9001/id=2/base_port=21020
