base: {{.ConfRootDir}}/hbase/common/common.yaml

cluster:
  project: hbase
  cluster_name: test-hbase
  main_process: java
  package_name: hbase-1.2.6-bin.tar.gz
  package_md5sum: e2b28a6a0bb1699f853bd9ad9a813b2c
  dependencies:
    - {{.ConfRootDir}}/zookeeper/test-zk.yaml
    - {{.ConfRootDir}}/hdfs/test-hdfs.yaml

jobs:
  master:
    hosts:
      - 127.0.0.1:9001/id=0/base_port=30100
      - 127.0.0.1:9001/id=1/base_port=30200
  regionserver:
    hosts:
      - 127.0.0.1:9001/id=0/base_port=31000
      - 127.0.0.1:9001/id=1/base_port=31010
      - 127.0.0.1:9001/id=2/base_port=31020
