base: {{.ConfRootDir}}/zookeeper/common/common.yaml

cluster:
  cluster_name: test-zk
  java_home: java
  package_name: zookeeper-3.4.11.tar.gz
  package_md5sum: 55aec6196ed9fa4c451cb5ae4a1f42d8

jobs:
  zkServer:
    config:
      zoo.cfg:
        - tick_time=2000
        - server.1=127.0.0.1:2188:3188
        - server.2=127.0.0.1:2288:3288
        - server.3=127.0.0.1:2388:3388
        - server.4=127.0.0.1:2488:3488
        - server.5=127.0.0.1:2588:3588
    hosts:
      127.0.0.1/port=9001/id=1:  # host.1
        config:
          zoo.cfg:
            - clientPort=2181
      127.0.0.1/port=9001/id=2:  # host.2
        config:
          zoo.cfg:
            - clientPort=2281
      127.0.0.1/port=9001/id=3:  # host.3
        config:
          zoo.cfg:
            - clientPort=2381
      127.0.0.1/port=9002/id=4:  # host.4
        config:
          zoo.cfg:
            - clientPort=2481
      127.0.0.1/port=9002/id=5:  # host.5
        config:
          zoo.cfg:
            - clientPort=2581
  zkCli:
    main_entry:
      extra_args: -server 127.0.0.1:2181,127.0.0.1:2281,127.0.0.1:2381,127.0.0.1:2481,127.0.0.1:2581