jobs:
  job_common:
    super_job: remote
    jvm_opts:
      - -XX:+DisableExplicitGC
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath={{.PkgStdoutDir}}
      - -XX:+PrintGCApplicationStoppedTime
      - -XX:+UseConcMarkSweepGC
      - -XX:+UseMembar
      - -verbose:gc
      - -XX:+PrintGCDetails
      - -XX:+PrintHeapAtGC
      - -XX:+PrintGCDateStamps
      - -Xloggc:{{.PkgStdoutDir}}/hbase_gc.log
    jvm_properties:
      - java.net.preferIPv4Stack=true
      - jute.maxbuffer=10240000
      - hbase.log.dir={{.PkgLogDir}}
      - hbase.home.dir={{.PkgRootDir}}
      - hbase.root.logger=INFO,RFA
    config:
      hbase-site.xml:
        - hbase.cluster.distributed=true
        - hbase.rootdir=hdfs://%{dependencies.1.namenode.0.host}:%{dependencies.1.namenode.0.base_port}/hbase/%{cluster.name}
        - hbase.zookeeper.quorum=%{dependencies.0.zkServer.server_list}
        - hbase.security.authentication=simple
        - hbase.table.sanity.checks=false
        - zookeeper.znode.parent=/hbase/%{cluster.name}
      log4j.properties:
        file: {{.ConfRootDir}}/hbase/common/log4j.properties
    classpath:
      - {{.PkgConfDir}}
      - {{.PkgRootDir}}/lib/*
      - {{.PkgRootDir}}/lib/ruby/*
      - {{.PkgRootDir}}/*
      - $AgentRootDir/.packages/e78fd41708aaa8d286ed2dcde0a5b645/apache-phoenix-4.13.1-HBase-1.2-bin/*
  master:
    super_job: job_common
    jvm_properties:
      - hbase.log.file=master.log
    config:
      hbase-site.xml:
        - hbase.master.port=%{master.x.base_port}
        - hbase.master.info.port=%{master.x.base_port+1}
    main_entry:
      java_class: org.apache.hadoop.hbase.master.HMaster
      extra_args: start
  regionserver:
    super_job: job_common
    jvm_properties:
      - hbase.log.file=regionserver.log
    config:
      hbase-site.xml:
        - hbase.regionserver.port=%{regionserver.x.base_port}
        - hbase.regionserver.info.port=%{regionserver.x.base_port+1}
    main_entry:
      java_class: org.apache.hadoop.hbase.regionserver.HRegionServer
      extra_args: start
  # Shell command job, not service job.
  shell:
    super_job: job_common
    jvm_opts:
      - -Dproc_shell
    jvm_properties:
      - hbase.ruby.sources={{.PkgRootDir}}/lib/ruby
      - hbase.root.logger=INFO,console
      - hbase.security.logger=INFO,console
    main_entry:
      java_class: org.jruby.Main
      extra_args: -X+O {{.PkgRootDir}}/bin/hirb.rb
