base: {{.ConfRootDir}}/yarn/common/common.yaml

cluster:
  project: yarn
  cluster_name: test-yarn
  main_process: java
  package_name: hadoop-2.6.5.tar.gz
  package_md5sum: 967c24f3c15fcdd058f34923e92ce8ac
  dependencies:
    - {{.ConfRootDir}}/hdfs/test-hdfs.yaml

jobs:
  resourcemanager:
    hosts:
      - 127.0.0.1:9001/id=0/base_port=4010
  nodemanager:
    hosts:
      - 127.0.0.1:9001/id=0/base_port=4020
  historyserver:
    hosts:
      - 127.0.0.1:9001/id=0/base_port=4100
  proxyserver:
    hosts:
      - 127.0.0.1:9001/id=0/base_port=4200
  timelineserver:
    hosts:
      - 127.0.0.1:9001/id=0/base_port=4300
